### ISSUE TITLE
EDDN: horizons/odyssey flags appear to be incorrect

### ISSUE THREAD

**Issue by HansAcker** [Asrothear/UGC-App#2]
Hello.
I noticed messages by UGC App that had their horizons/odyssey flags set to false while the same event submitted through another tool does set them. I am not quite sure on the EDDN guidance but I think these flags should be omitted if the gameversion/variant can't be determined.  [My code](https://eddn-realtime.space/) would then color it as "Unknown" instead of "base game".

```
{
  "$schemaRef": "https://eddn.edcd.io/schemas/journal/1",
  "header": {
    "gamebuild": "",
    "gameversion": "",
    "gatewayTimestamp": "2024-07-18T09:00:24.838397Z",
    "softwareName": "UGC App",
    "softwareVersion": "0.8.1-alpha",
    "uploaderID": "d86af335180dc6c550792d521d83207fa42f0573"
  },
  "message": {
...
    "Taxi": false,
    "event": "FSDJump",
    "horizons": false,
    "odyssey": false,
    "timestamp": "2024-07-18T09:00:24Z"
  }
}
```

Same event with the same timestamp and star system:
```
{
  "$schemaRef": "https://eddn.edcd.io/schemas/journal/1",
  "header": {
    "gamebuild": "r303387/r0 ",
    "gameversion": "4.0.0.1807",
    "gatewayTimestamp": "2024-07-18T09:00:24.690861Z",
    "softwareName": "E:D Market Connector [Windows]",
    "softwareVersion": "5.11.2",
    "uploaderID": "c09acfe085be23cc02fe25a1bd2e12b48d337b7b"
  },
  "message": {
...
    "Taxi": false,
    "event": "FSDJump",
    "horizons": true,
    "odyssey": true,
    "timestamp": "2024-07-18T09:00:24Z"
  }
}
```

A similar pair:
```
{
  "$schemaRef": "https://eddn.edcd.io/schemas/journal/1",
  "header": {
    "gamebuild": "",
    "gameversion": "",
    "gatewayTimestamp": "2024-07-18T09:11:43.795196Z",
    "softwareName": "UGC App",
    "softwareVersion": "0.8.1-alpha",
    "uploaderID": "83620bc60df0df376d4c1681b31a66d050f89050"
  },
  "message": {
...
    "Taxi": false,
    "event": "Location",
    "horizons": false,
    "odyssey": false,
    "timestamp": "2024-07-18T09:11:41Z"
  }
}


{
  "$schemaRef": "https://eddn.edcd.io/schemas/journal/1",
  "header": {
    "gamebuild": "r303387/r0 ",
    "gameversion": "4.0.0.1807",
    "gatewayTimestamp": "2024-07-18T09:11:41.747138Z",
    "softwareName": "E:D Market Connector [Windows]",
    "softwareVersion": "5.11.2",
    "uploaderID": "9ef0d411133796f3a7b1e01713cb6876508b29dc"
  },
  "message": {
...
    "Taxi": false,
    "event": "Location",
    "horizons": true,
    "odyssey": true,
    "timestamp": "2024-07-18T09:11:41Z"
  }
}
```

**Comment by Fynnoverse** [comment]
Thanks for pointing this out, I will have a look at this.
Maybe I can provide a fix until tomorrow

**Comment by Fynnoverse** [comment]
According to [EDDN´s gameversions and gamebuild Entry](https://github.com/EDCD/EDDN/blob/live/docs/Developers.md#gameversions-and-gamebuild)
the value has to be `""`

> [...] For gamebuild you MUST use the value of the build field in the data source, following the same logic as for gameversion above, else send as "". [...]

Omitting would be not the correct way, I will look up why there is no gamebuild and gameversion to make sure it's more reliable

**Comment by Fynnoverse** [comment]
Do you have some more Data from the affected messages, so i can look them up in my log?

**Comment by HansAcker** [comment]
> Omitting would be not the correct way, I will look up why there is no gamebuild and gameversion to make sure it's more reliable

Oh, I meant omitting the horizons/odyssey flags from the message:
https://github.com/EDCD/EDDN/blob/master/docs/Developers.md#horizons-and-odyssey-flags
>Where the Schema allows for them, horizons and odyssey keys MUST be added with appropriate boolean values. null is not allowed in the values, so **if you cannot determine a value do not include that key at all**.


> Do you have some more Data from the affected messages, so i can look them up in my log?

There's an archive of EDDN messages at https://edgalaxydata.space/EDDN/ indexed by event type, so for example
```
curl https://edgalaxydata.space/EDDN/Journal.Docked-2024-07-18.jsonl |grep "UGC App" |jq '[.header.softwareVersion, .header.gameversion, .message.timestamp, .message.horizons, .message.odyssey]'
```

There are several message where gameversion and the flags are set correctly.

```
...
[
  "0.8.1-alpha",
  "4.0.0.1807",
  "2024-07-18T08:36:53Z",
  true,
  true
]
[
  "0.8.1-alpha",
  "",
  "2024-07-18T09:05:41Z",
  false,
  false
]
...
```

**Comment by Fynnoverse** [comment]
Sorry, my mistake.

Will add the removal if no gameversions **and** no gamebuild is set.
Further, I will check why that's the case

The thing is that the horizons/odyssey flags are existent, but not the build or version

For now, I will adjust it so that if neither is set, the horizons/odyssey flags are omitted

**Comment by Fynnoverse** [comment]
https://github.com/Asrothear/UGC-App/commit/74a78c68a2ea649fd68cc16773d20e3d067f6ca5
